/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Partners */
        get: operations["list_partners_partners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/{partner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Partner */
        get: operations["get_partner_partners__partner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Referrals */
        get: operations["list_referrals_referrals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{referral_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Referral */
        get: operations["get_referral_referrals__referral_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dev Users */
        get: operations["list_dev_users_dev_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CarrierRef */
        CarrierRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * DevUserOut
         * @description A person the development "View as" switcher can act as.
         */
        DevUserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "rep";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PartnerOut */
        PartnerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "Loan officer" | "Realtor" | "Financial advisor" | "Other";
            /** Type Other */
            type_other: string | null;
            /** Business Name */
            business_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Territory */
            territory: string;
            primary_rep: components["schemas"]["UserRef"] | null;
            /** Do Not Contact */
            do_not_contact: boolean;
            /** Sensitive Items */
            sensitive_items: string;
            /** Production */
            production: components["schemas"]["ProductionOut"][];
        };
        /** PartnerRef */
        PartnerRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Business Name */
            business_name: string;
        };
        /** ProductionOut */
        ProductionOut: {
            /** Year */
            year: number;
            /** Amount */
            amount: number;
            /** Verified */
            verified: boolean;
        };
        /** ReferralOut */
        ReferralOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            partner: components["schemas"]["PartnerRef"];
            /** Client Name */
            client_name: string;
            /** Client Address */
            client_address: string | "blocked";
            /** Client Birthday */
            client_birthday: string | "blocked" | null;
            /** Sensitive Items */
            sensitive_items: string;
            /**
             * Line Of Business
             * @enum {string}
             */
            line_of_business: "Auto" | "Home" | "Umbrella" | "Life" | "Commercial";
            carrier: components["schemas"]["CarrierRef"];
            /**
             * Referred Date
             * Format: date
             */
            referred_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "referred" | "contacted" | "quoted" | "bound" | "lost";
            /** Premium */
            premium: number | null;
            /** Bound Date */
            bound_date: string | null;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /** StepOut */
        StepOut: {
            /**
             * Step
             * @enum {string}
             */
            step: "introduction" | "contact" | "quote" | "bind";
            rep: components["schemas"]["UserRef"];
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** UserRef */
        UserRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_partners_partners_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_partner_partners__partner_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path: {
                partner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_referrals_referrals_get: {
        parameters: {
            query?: {
                partner_id?: string | null;
            };
            header?: {
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_referral_referrals__referral_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dev_users_dev_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevUserOut"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
