/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Partners
         * @description Partners with their referral numbers for the period: filtered, sorted and paged.
         */
        get: operations["list_partners_partners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/{partner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Partner */
        get: operations["get_partner_partners__partner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Referrals
         * @description A filtered, sorted page of the referrals this viewer may see.
         */
        get: operations["list_referrals_referrals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline Board
         * @description Open referrals, plus those bound or lost in the last 30 days.
         */
        get: operations["pipeline_board_referrals_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{referral_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Referral */
        get: operations["get_referral_referrals__referral_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{referral_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Status
         * @description Move a referral on the pipeline (see app/pipeline.py for the rules).
         */
        post: operations["change_status_referrals__referral_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{referral_id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activities
         * @description Logged touches on a referral, newest first. Whoever can see the referral sees these.
         */
        get: operations["list_activities_referrals__referral_id__activities_get"];
        put?: never;
        /**
         * Log Activity
         * @description Log a call, email or meeting with the client. Doesn't change steps or credit.
         */
        post: operations["log_activity_referrals__referral_id__activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the API thinks is asking.
         */
        get: operations["me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Team
         * @description Everyone active on the team, e.g. for 'who made contact'.
         */
        get: operations["list_team_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/reps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reps
         * @description Active reps, e.g. for an admin choosing who gets credit for a pipeline move.
         */
        get: operations["list_reps_users_reps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Views */
        get: operations["list_views_views_get"];
        put?: never;
        /** Save View */
        post: operations["save_view_views_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete View */
        delete: operations["delete_view_views__view_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dev Users */
        get: operations["list_dev_users_dev_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityIn
         * @description Log a touch. Rules beyond these types (dates, who) are checked in the endpoint.
         */
        ActivityIn: {
            /**
             * Rep Id
             * Format: uuid
             */
            rep_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Method
             * @enum {string}
             */
            method: "In person" | "Phone" | "Email";
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** ActivityOut */
        ActivityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Method
             * @enum {string}
             */
            method: "In person" | "Phone" | "Email";
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Notes */
            notes: string;
            rep: components["schemas"]["UserRef"];
            logged_by: components["schemas"]["UserRef"];
        };
        /** CarrierRef */
        CarrierRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * DevUserOut
         * @description A person the development "View as" switcher can act as.
         */
        DevUserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "rep";
        };
        /** FieldErrorOut */
        FieldErrorOut: {
            /** Message */
            message: string;
            /** Field */
            field: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Me
         * @description The signed-in person.
         */
        Me: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "rep";
        };
        /** PartnerOut */
        PartnerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "Loan officer" | "Realtor" | "Financial advisor" | "Other";
            /** Type Other */
            type_other: string | null;
            /** Business Name */
            business_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Territory */
            territory: string;
            primary_rep: components["schemas"]["UserRef"] | null;
            /** Do Not Contact */
            do_not_contact: boolean;
            /** Sensitive Items */
            sensitive_items: string;
            /** Production */
            production: components["schemas"]["ProductionOut"][];
        };
        /** PartnerPage */
        PartnerPage: {
            /** Items */
            items: components["schemas"]["PartnerRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PartnerRef */
        PartnerRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Business Name */
            business_name: string;
        };
        /** PartnerRow */
        PartnerRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "Loan officer" | "Realtor" | "Financial advisor" | "Other";
            /** Type Other */
            type_other: string | null;
            /** Business Name */
            business_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Territory */
            territory: string;
            primary_rep: components["schemas"]["UserRef"] | null;
            /** Do Not Contact */
            do_not_contact: boolean;
            /** Sensitive Items */
            sensitive_items: string;
            /** Production */
            production: components["schemas"]["ProductionOut"][];
            stats: components["schemas"]["PartnerStats"];
        };
        /**
         * PartnerStats
         * @description A partner's referral numbers for the chosen period (referrals referred in it).
         */
        PartnerStats: {
            /** Referrals */
            referrals: number;
            /** Bound */
            bound: number;
            /** Close Rate */
            close_rate: number | null;
            /** Bound Premium */
            bound_premium: number;
            /** Last Referred */
            last_referred: string | null;
        };
        /** ProductionOut */
        ProductionOut: {
            /** Year */
            year: number;
            /** Amount */
            amount: number;
            /** Verified */
            verified: boolean;
        };
        /** ReferralOut */
        ReferralOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            partner: components["schemas"]["PartnerRef"];
            /** Client Name */
            client_name: string;
            /** Client Address */
            client_address: string | "blocked";
            /** Client Birthday */
            client_birthday: string | "blocked" | null;
            /** Sensitive Items */
            sensitive_items: string;
            /**
             * Line Of Business
             * @enum {string}
             */
            line_of_business: "Auto" | "Home" | "Umbrella" | "Life" | "Commercial";
            carrier: components["schemas"]["CarrierRef"];
            /**
             * Referred Date
             * Format: date
             */
            referred_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "referred" | "contacted" | "quoted" | "bound" | "lost";
            /** Premium */
            premium: number | null;
            /** Bound Date */
            bound_date: string | null;
            /** Lost Date */
            lost_date: string | null;
            /**
             * Last Touch
             * Format: date
             */
            last_touch: string;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /**
         * ReferralPage
         * @description One page of a filtered, sorted referral list.
         */
        ReferralPage: {
            /** Items */
            items: components["schemas"]["ReferralOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** SavedViewIn */
        SavedViewIn: {
            /**
             * List
             * @enum {string}
             */
            list: "referrals" | "partners";
            /** Name */
            name: string;
            /**
             * Query
             * @default
             */
            query: string;
        };
        /** SavedViewOut */
        SavedViewOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * List
             * @enum {string}
             */
            list: "referrals" | "partners";
            /** Name */
            name: string;
            /** Query */
            query: string;
        };
        /**
         * StatusChange
         * @description Move a referral on the pipeline. See app/pipeline.py for the rules.
         */
        StatusChange: {
            /**
             * Status
             * @enum {string}
             */
            status: "referred" | "contacted" | "quoted" | "bound" | "lost";
            /** Premium */
            premium?: number | string | null;
            /** Bound Date */
            bound_date?: string | null;
            /** Credit Rep Id */
            credit_rep_id?: string | null;
        };
        /** StepOut */
        StepOut: {
            /**
             * Step
             * @enum {string}
             */
            step: "introduction" | "contact" | "quote" | "bind";
            rep: components["schemas"]["UserRef"];
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** UserRef */
        UserRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_partners_partners_get: {
        parameters: {
            query?: {
                type?: ("Loan officer" | "Realtor" | "Financial advisor" | "Other")[];
                primary_rep_id?: string | null;
                unassigned?: boolean | null;
                do_not_contact?: boolean | null;
                no_referrals?: boolean | null;
                q?: string | null;
                period?: "r12" | "ytd" | "all";
                sort?: "name" | "-name" | "referrals" | "-referrals" | "bound" | "-bound" | "close_rate" | "-close_rate" | "bound_premium" | "-bound_premium" | "last_referred" | "-last_referred";
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_partner_partners__partner_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path: {
                partner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_referrals_referrals_get: {
        parameters: {
            query?: {
                status?: ("referred" | "contacted" | "quoted" | "bound" | "lost")[];
                line?: ("Auto" | "Home" | "Umbrella" | "Life" | "Commercial")[];
                partner_id?: string | null;
                rep_id?: string | null;
                stale_days?: number | null;
                bound_from?: string | null;
                bound_to?: string | null;
                has_premium?: boolean | null;
                q?: string | null;
                sort?: "referred_date" | "-referred_date" | "last_touch" | "-last_touch" | "client_name" | "-client_name" | "premium" | "-premium" | "status" | "-status";
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_board_referrals_pipeline_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_referral_referrals__referral_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_referrals__referral_id__status_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    list_activities_referrals__referral_id__activities_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_activity_referrals__referral_id__activities_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    me_users_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_users_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reps_users_reps_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_views_views_get: {
        parameters: {
            query: {
                list: "referrals" | "partners";
            };
            header?: {
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedViewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_view_views_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedViewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedViewOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    delete_view_views__view_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
            };
            path: {
                view_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dev_users_dev_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevUserOut"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
