/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Partners
         * @description Partners with their referral numbers for the period: filtered, sorted and paged.
         */
        get: operations["list_partners_partners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/{partner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Partner */
        get: operations["get_partner_partners__partner_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Partner
         * @description Edit shared partner facts. Anyone may change do-not-contact, the "do not discuss" note and the
         *     territory; only admins reassign the primary rep (v1's rules, plus territory for anyone).
         */
        patch: operations["update_partner_partners__partner_id__patch"];
        trace?: never;
    };
    "/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Referrals
         * @description A filtered, sorted page of the referrals this viewer may see.
         */
        get: operations["list_referrals_referrals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline Board
         * @description Open referrals, plus those bound or lost in the last 30 days.
         */
        get: operations["pipeline_board_referrals_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{referral_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Referral */
        get: operations["get_referral_referrals__referral_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Referral
         * @description Fix a referral's line, carrier or premium without a pipeline move.
         *
         *     Anyone who can see it may edit before bind. Once bound these fields drive commission (carrier and line
         *     set the rate), so only admins change them. Premium exists from quoted on: it can't be set on a referral
         *     that hasn't been quoted, and a lost referral's premium stays as it was when lost.
         */
        patch: operations["update_referral_referrals__referral_id__patch"];
        trace?: never;
    };
    "/referrals/{referral_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Status
         * @description Move a referral on the pipeline (see app/pipeline.py for the rules).
         */
        post: operations["change_status_referrals__referral_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{referral_id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activities
         * @description Logged touches on a referral, newest first. Whoever can see the referral sees these.
         */
        get: operations["list_activities_referrals__referral_id__activities_get"];
        put?: never;
        /**
         * Log Activity
         * @description Log a call, email or meeting with the client. Doesn't change steps or credit.
         */
        post: operations["log_activity_referrals__referral_id__activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the API thinks is asking.
         */
        get: operations["me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Team
         * @description Everyone active on the team, e.g. for 'who made contact'.
         */
        get: operations["list_team_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/reps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reps
         * @description Active reps, e.g. for an admin choosing who gets credit for a pipeline move.
         */
        get: operations["list_reps_users_reps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Views */
        get: operations["list_views_views_get"];
        put?: never;
        /** Save View */
        post: operations["save_view_views_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete View */
        delete: operations["delete_view_views__view_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carriers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Carriers */
        get: operations["list_carriers_carriers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress */
        get: operations["progress_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/reps/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Rep Goal */
        put: operations["set_rep_goal_goals_reps__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Company Goal */
        put: operations["set_company_goal_goals_company_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{referral_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Referral History */
        get: operations["referral_history_referrals__referral_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/{partner_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partner History */
        get: operations["partner_history_partners__partner_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign In */
        post: operations["sign_in_auth_sign_in_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Out */
        post: operations["sign_out_auth_sign_out_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out-everywhere": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Out Everywhere */
        post: operations["sign_out_everywhere_auth_sign_out_everywhere_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change your own password. Needs a real session and the current password (which counts as a sign-in
         *     attempt, so this can't be used to guess it). Every other session of yours ends.
         */
        post: operations["change_password_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/links/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Link
         * @description Whether a setup or reset link still works, and whose it is (to greet them). The token travels in the
         *     body, never the URL, so it stays out of server logs.
         */
        post: operations["check_link_auth_links_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/links/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem Link
         * @description Set a password through a one-time link, and sign in. Ends any other session the person had.
         */
        post: operations["redeem_link_auth_links_redeem_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List People */
        get: operations["list_people_team_get"];
        put?: never;
        /** Add Person */
        post: operations["add_person_team_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team/{user_id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * New Link
         * @description A setup link (no password yet) or a reset link (forgotten password). The old password keeps working
         *     until the link is used; using it ends every session the person had.
         */
        post: operations["new_link_team__user_id__link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Person */
        patch: operations["update_person_team__user_id__patch"];
        trace?: never;
    };
    "/dev/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dev Users */
        get: operations["list_dev_users_dev_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityIn
         * @description Log a touch. Rules beyond these types (dates, who) are checked in the endpoint.
         */
        ActivityIn: {
            /**
             * Rep Id
             * Format: uuid
             */
            rep_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Method
             * @enum {string}
             */
            method: "In person" | "Phone" | "Email";
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** ActivityOut */
        ActivityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Method
             * @enum {string}
             */
            method: "In person" | "Phone" | "Email";
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Notes */
            notes: string;
            rep: components["schemas"]["UserRef"];
            logged_by: components["schemas"]["UserRef"];
        };
        /** CarrierRef */
        CarrierRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** CompanyGoalIn */
        "CompanyGoalIn-Input": {
            /** Close Rate */
            close_rate: number | string | null;
        };
        /** CompanyGoalIn */
        "CompanyGoalIn-Output": {
            /** Close Rate */
            close_rate: string | null;
        };
        /**
         * CompanyProgress
         * @description Company totals, for admins.
         */
        CompanyProgress: {
            clients: components["schemas"]["Metric"];
            sales: components["schemas"]["Metric"];
            close_rate: components["schemas"]["Metric"];
        };
        /**
         * CompanyShare
         * @description What a rep sees of the company: progress as a share of goal, never company dollars or counts.
         */
        CompanyShare: {
            /** Clients Pct Of Goal */
            clients_pct_of_goal: number | null;
            /** Sales Pct Of Goal */
            sales_pct_of_goal: number | null;
            /** Close Rate */
            close_rate: number | null;
            /** Close Rate Goal */
            close_rate_goal: number | null;
        };
        /**
         * DevUserOut
         * @description A person the development "View as" switcher can act as.
         */
        DevUserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "rep";
        };
        /**
         * DigestData
         * @description A weekly digest as stored in notifications.data. A rep's holds only their own numbers; an admin's
         *     adds the company and every rep, the same split as GET /progress.
         */
        DigestData: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /**
             * Week End
             * Format: date
             */
            week_end: string;
            mine?: components["schemas"]["WeekTally"] | null;
            /**
             * Stale
             * @default 0
             */
            stale: number;
            company?: components["schemas"]["WeekTally"] | null;
            /**
             * Reps
             * @default []
             */
            reps: components["schemas"]["RepWeek"][];
        };
        /** FieldChange */
        FieldChange: {
            /** Field */
            field: string;
            /**
             * Redacted
             * @default false
             */
            redacted: boolean;
            /** Before */
            before?: string | number | boolean | null;
            /** After */
            after?: string | number | boolean | null;
            /** Before Label */
            before_label?: string | null;
            /** After Label */
            after_label?: string | null;
        };
        /** FieldErrorOut */
        FieldErrorOut: {
            /** Message */
            message: string;
            /** Field */
            field: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEvent */
        HistoryEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            actor: components["schemas"]["UserRef"] | null;
            /** Actor Label */
            actor_label: string | null;
            /**
             * Action
             * @enum {string}
             */
            action: "insert" | "update" | "delete" | "restore";
            /** Entity */
            entity: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Changes */
            changes: components["schemas"]["FieldChange"][];
        };
        /** LinkInfo */
        LinkInfo: {
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "setup" | "reset";
            /** Name */
            name: string;
        };
        /**
         * LinkOut
         * @description A one-time link's token. The web app turns it into a URL; the API never stores the token itself.
         */
        LinkOut: {
            /** Token */
            token: string;
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "setup" | "reset";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** LinkRedeem */
        LinkRedeem: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** LinkToken */
        LinkToken: {
            /** Token */
            token: string;
        };
        /**
         * Me
         * @description The signed-in person.
         */
        Me: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "rep";
        };
        /**
         * Metric
         * @description One progress number for the month so far, with its comparisons.
         *
         *     Units: clients are a count, sales are dollars, close rate is a fraction (0.64 = 64%); a close-rate
         *     difference is in fraction points (0.05 = 5 pts).
         */
        Metric: {
            /** Value */
            value: number | null;
            /** Goal */
            goal: number | null;
            /** Vs Last Month */
            vs_last_month: number | null;
            /** Vs Team */
            vs_team: number | null;
            /** Vs Team Pct */
            vs_team_pct: number | null;
        };
        /** NotificationOut */
        NotificationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "stale_referral" | "weekly_digest";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read At */
            read_at: string | null;
            stale?: components["schemas"]["StaleReferralRef"] | null;
            digest?: components["schemas"]["DigestData"] | null;
        };
        /** NotificationPage */
        NotificationPage: {
            /** Items */
            items: components["schemas"]["NotificationOut"][];
            /** Unread */
            unread: number;
        };
        /** PartnerOut */
        PartnerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "Loan officer" | "Realtor" | "Financial advisor" | "Other";
            /** Type Other */
            type_other: string | null;
            /** Business Name */
            business_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Territory */
            territory: string;
            primary_rep: components["schemas"]["UserRef"] | null;
            /** Do Not Contact */
            do_not_contact: boolean;
            /** Sensitive Items */
            sensitive_items: string;
            /** Production */
            production: components["schemas"]["ProductionOut"][];
        };
        /** PartnerPage */
        PartnerPage: {
            /** Items */
            items: components["schemas"]["PartnerRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * PartnerPatch
         * @description Inline edit of a partner. Only fields present in the request change (`model_fields_set`),
         *     so "primary_rep_id": null unassigns, while leaving it out leaves it alone.
         */
        PartnerPatch: {
            /** Do Not Contact */
            do_not_contact?: boolean | null;
            /** Sensitive Items */
            sensitive_items?: string | null;
            /** Territory */
            territory?: string | null;
            /** Primary Rep Id */
            primary_rep_id?: string | null;
        };
        /** PartnerRef */
        PartnerRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Business Name */
            business_name: string;
        };
        /** PartnerRow */
        PartnerRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "Loan officer" | "Realtor" | "Financial advisor" | "Other";
            /** Type Other */
            type_other: string | null;
            /** Business Name */
            business_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Territory */
            territory: string;
            primary_rep: components["schemas"]["UserRef"] | null;
            /** Do Not Contact */
            do_not_contact: boolean;
            /** Sensitive Items */
            sensitive_items: string;
            /** Production */
            production: components["schemas"]["ProductionOut"][];
            stats: components["schemas"]["PartnerStats"];
        };
        /**
         * PartnerStats
         * @description A partner's referral numbers for the chosen period (referrals referred in it).
         */
        PartnerStats: {
            /** Referrals */
            referrals: number;
            /** Bound */
            bound: number;
            /** Close Rate */
            close_rate: number | null;
            /** Bound Premium */
            bound_premium: number;
            /** Last Referred */
            last_referred: string | null;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PersonCreated */
        PersonCreated: {
            person: components["schemas"]["PersonOut"];
            link: components["schemas"]["LinkOut"];
        };
        /** PersonIn */
        PersonIn: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "rep";
        };
        /**
         * PersonOut
         * @description A person as admins see them on the Team page. Never includes password hashes or tokens.
         */
        PersonOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "rep";
            /** Active */
            active: boolean;
            /** Has Password */
            has_password: boolean;
            /** Last Sign In At */
            last_sign_in_at: string | null;
        };
        /** PersonPatch */
        PersonPatch: {
            /** Active */
            active?: boolean | null;
            /** Role */
            role?: ("admin" | "rep") | null;
        };
        /** ProductionOut */
        ProductionOut: {
            /** Year */
            year: number;
            /** Amount */
            amount: number;
            /** Verified */
            verified: boolean;
        };
        /** ProgressOut */
        ProgressOut: {
            /** Month */
            month: string;
            /**
             * Through
             * Format: date
             */
            through: string;
            /**
             * Compared Through
             * Format: date
             */
            compared_through: string;
            company: components["schemas"]["CompanyProgress"] | null;
            company_share: components["schemas"]["CompanyShare"] | null;
            /** Reps */
            reps: components["schemas"]["RepProgress"][];
        };
        /** ReferralOut */
        ReferralOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            partner: components["schemas"]["PartnerRef"];
            /** Client Name */
            client_name: string;
            /** Client Address */
            client_address: string | "blocked";
            /** Client Birthday */
            client_birthday: string | "blocked" | null;
            /** Sensitive Items */
            sensitive_items: string;
            /**
             * Line Of Business
             * @enum {string}
             */
            line_of_business: "Auto" | "Home" | "Umbrella" | "Life" | "Commercial";
            carrier: components["schemas"]["CarrierRef"];
            /**
             * Referred Date
             * Format: date
             */
            referred_date: string;
            /**
             * Status
             * @enum {string}
             */
            status: "referred" | "contacted" | "quoted" | "bound" | "lost";
            /** Premium */
            premium: number | null;
            /** Bound Date */
            bound_date: string | null;
            /** Lost Date */
            lost_date: string | null;
            /**
             * Last Touch
             * Format: date
             */
            last_touch: string;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /**
         * ReferralPage
         * @description One page of a filtered, sorted referral list.
         */
        ReferralPage: {
            /** Items */
            items: components["schemas"]["ReferralOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ReferralPatch
         * @description Inline edit of a referral's policy details. Pipeline moves go through /status instead.
         */
        ReferralPatch: {
            /** Line Of Business */
            line_of_business?: ("Auto" | "Home" | "Umbrella" | "Life" | "Commercial") | null;
            /** Carrier Id */
            carrier_id?: string | null;
            /** Premium */
            premium?: number | string | null;
        };
        /** RepGoalIn */
        "RepGoalIn-Input": {
            /** Clients */
            clients: number;
            /** Sales */
            sales: number | string;
        };
        /** RepGoalIn */
        "RepGoalIn-Output": {
            /** Clients */
            clients: number;
            /** Sales */
            sales: string;
        };
        /** RepProgress */
        RepProgress: {
            rep: components["schemas"]["UserRef"];
            clients: components["schemas"]["Metric"];
            sales: components["schemas"]["Metric"];
            close_rate: components["schemas"]["Metric"];
        };
        /** RepWeek */
        RepWeek: {
            /** New Referrals */
            new_referrals: number;
            /** Clients */
            clients: number;
            /** Sales */
            sales: number;
            /** Close Rate */
            close_rate: number | null;
            rep: components["schemas"]["UserRef"];
        };
        /** SavedViewIn */
        SavedViewIn: {
            /**
             * List
             * @enum {string}
             */
            list: "referrals" | "partners";
            /** Name */
            name: string;
            /**
             * Query
             * @default
             */
            query: string;
        };
        /** SavedViewOut */
        SavedViewOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * List
             * @enum {string}
             */
            list: "referrals" | "partners";
            /** Name */
            name: string;
            /** Query */
            query: string;
        };
        /**
         * SessionOut
         * @description A new session. The token is shown this once; the web app keeps it in an httpOnly cookie.
         */
        SessionOut: {
            /** Token */
            token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["Me"];
        };
        /** SignIn */
        SignIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * StaleReferralRef
         * @description The referral a stale nudge points at, looked up at read time through the reader's own scoping.
         */
        StaleReferralRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Client Name */
            client_name: string;
            partner: components["schemas"]["PartnerRef"];
            /**
             * Status
             * @enum {string}
             */
            status: "referred" | "contacted" | "quoted" | "bound" | "lost";
            /**
             * Last Touch
             * Format: date
             */
            last_touch: string;
            /** Days Since Touch */
            days_since_touch: number;
        };
        /**
         * StatusChange
         * @description Move a referral on the pipeline. See app/pipeline.py for the rules.
         */
        StatusChange: {
            /**
             * Status
             * @enum {string}
             */
            status: "referred" | "contacted" | "quoted" | "bound" | "lost";
            /** Premium */
            premium?: number | string | null;
            /** Bound Date */
            bound_date?: string | null;
            /** Credit Rep Id */
            credit_rep_id?: string | null;
        };
        /** StepOut */
        StepOut: {
            /**
             * Step
             * @enum {string}
             */
            step: "introduction" | "contact" | "quote" | "bind";
            rep: components["schemas"]["UserRef"];
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** UserRef */
        UserRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WeekTally
         * @description One person's (or the company's) numbers for a week. Same definitions as the dashboard (app/progress.py).
         */
        WeekTally: {
            /** New Referrals */
            new_referrals: number;
            /** Clients */
            clients: number;
            /** Sales */
            sales: number;
            /** Close Rate */
            close_rate: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_partners_partners_get: {
        parameters: {
            query?: {
                type?: ("Loan officer" | "Realtor" | "Financial advisor" | "Other")[];
                primary_rep_id?: string | null;
                unassigned?: boolean | null;
                do_not_contact?: boolean | null;
                no_referrals?: boolean | null;
                min_referrals?: number | null;
                q?: string | null;
                period?: "r12" | "ytd" | "all";
                sort?: ("name" | "-name" | "referrals" | "-referrals" | "bound" | "-bound" | "close_rate" | "-close_rate" | "bound_premium" | "-bound_premium" | "last_referred" | "-last_referred")[];
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_partner_partners__partner_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                partner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_partner_partners__partner_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                partner_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartnerPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    list_referrals_referrals_get: {
        parameters: {
            query?: {
                status?: ("referred" | "contacted" | "quoted" | "bound" | "lost")[];
                line?: ("Auto" | "Home" | "Umbrella" | "Life" | "Commercial")[];
                partner_id?: string | null;
                rep_id?: string | null;
                stale_days?: number | null;
                bound_from?: string | null;
                bound_to?: string | null;
                has_premium?: boolean | null;
                q?: string | null;
                sort?: ("referred_date" | "-referred_date" | "last_touch" | "-last_touch" | "client_name" | "-client_name" | "premium" | "-premium" | "status" | "-status")[];
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_board_referrals_pipeline_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_referral_referrals__referral_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_referral_referrals__referral_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferralPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    change_status_referrals__referral_id__status_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    list_activities_referrals__referral_id__activities_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_activity_referrals__referral_id__activities_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    me_users_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_users_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reps_users_reps_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_views_views_get: {
        parameters: {
            query: {
                list: "referrals" | "partners";
            };
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedViewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_view_views_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedViewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedViewOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    delete_view_views__view_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                view_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_carriers_carriers_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_progress_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_rep_goal_goals_reps__user_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepGoalIn-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepGoalIn-Output"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    set_company_goal_goals_company_put: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyGoalIn-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyGoalIn-Output"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    referral_history_referrals__referral_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    partner_history_partners__partner_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                partner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_in_auth_sign_in_post: {
        parameters: {
            query?: never;
            header?: {
                "user-agent"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sign_out_auth_sign_out_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_everywhere_auth_sign_out_everywhere_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_auth_password_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    check_link_auth_links_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkToken"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeem_link_auth_links_redeem_post: {
        parameters: {
            query?: never;
            header?: {
                "user-agent"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRedeem"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    list_people_team_get: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_person_team_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonCreated"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    new_link_team__user_id__link_post: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    update_person_team__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-dev-user"?: string | null;
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldErrorOut"];
                };
            };
        };
    };
    list_dev_users_dev_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevUserOut"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
