"""saved views

Revision ID: 3c6a534c6ce9
Revises: e84645b35b65
Create Date: 2026-09-29 20:16:35.866615
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3c6a534c6ce9'
down_revision: str | Sequence[str] | None = 'e84645b35b65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_views',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('list', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('query', sa.String(), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("list IN ('referrals', 'partners')", name=op.f('ck_saved_views_list')),
    sa.CheckConstraint('char_length(name) BETWEEN 1 AND 60', name=op.f('ck_saved_views_name_length')),
    sa.CheckConstraint('char_length(query) <= 1000', name=op.f('ck_saved_views_query_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_views_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_views'))
    )
    op.create_index('uq_saved_views_user_id_list_name_live', 'saved_views', ['user_id', 'list', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_saved_views_user_id_list_name_live', table_name='saved_views', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('saved_views')
    # ### end Alembic commands ###
