"""referral lost date

Revision ID: d6a20eecc99d
Revises: 3a36dfed5c39
Create Date: 2026-09-29 15:31:41.340587
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd6a20eecc99d'
down_revision: str | Sequence[str] | None = '3a36dfed5c39'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('lost_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'lost_date')
    # ### end Alembic commands ###
