"""partners and referrals

Revision ID: 3a36dfed5c39
Revises: 
Create Date: 2026-09-29 13:13:32.650467
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3a36dfed5c39'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carriers'))
    )
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'rep')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_live', 'users', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('partners',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('type_other', sa.String(), nullable=True),
    sa.Column('business_name', sa.String(), server_default='', nullable=False),
    sa.Column('phone', sa.String(), server_default='', nullable=False),
    sa.Column('email', sa.String(), server_default='', nullable=False),
    sa.Column('territory', sa.String(), server_default='', nullable=False),
    sa.Column('primary_rep_id', sa.Uuid(), nullable=True),
    sa.Column('do_not_contact', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sensitive_items', sa.String(), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('Loan officer', 'Realtor', 'Financial advisor', 'Other')", name=op.f('ck_partners_type')),
    sa.ForeignKeyConstraint(['primary_rep_id'], ['users.id'], name=op.f('fk_partners_primary_rep_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners'))
    )
    op.create_index(op.f('ix_partners_primary_rep_id'), 'partners', ['primary_rep_id'], unique=False)
    op.create_table('partner_production',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partner_production_partner_id_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_production'))
    )
    op.create_index('uq_partner_production_partner_id_year_live', 'partner_production', ['partner_id', 'year'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('referrals',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_address', sa.String(), server_default='', nullable=False),
    sa.Column('client_birthday', sa.Date(), nullable=True),
    sa.Column('sensitive_items', sa.String(), server_default='', nullable=False),
    sa.Column('line_of_business', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.Uuid(), nullable=False),
    sa.Column('referred_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), server_default='referred', nullable=False),
    sa.Column('premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bound_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("line_of_business IN ('Auto', 'Home', 'Umbrella', 'Life', 'Commercial')", name=op.f('ck_referrals_line_of_business')),
    sa.CheckConstraint("status IN ('referred', 'contacted', 'quoted', 'bound', 'lost')", name=op.f('ck_referrals_status')),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], name=op.f('fk_referrals_carrier_id_carriers')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_referrals_partner_id_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals'))
    )
    op.create_index(op.f('ix_referrals_partner_id'), 'referrals', ['partner_id'], unique=False)
    op.create_table('referral_steps',
    sa.Column('referral_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('rep_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("step IN ('introduction', 'contact', 'quote', 'bind')", name=op.f('ck_referral_steps_step')),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_referral_steps_referral_id_referrals')),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], name=op.f('fk_referral_steps_rep_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_steps'))
    )
    op.create_index(op.f('ix_referral_steps_rep_id'), 'referral_steps', ['rep_id'], unique=False)
    op.create_index('uq_referral_steps_referral_id_step_live', 'referral_steps', ['referral_id', 'step'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_referral_steps_referral_id_step_live', table_name='referral_steps', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_referral_steps_rep_id'), table_name='referral_steps')
    op.drop_table('referral_steps')
    op.drop_index(op.f('ix_referrals_partner_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('uq_partner_production_partner_id_year_live', table_name='partner_production', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('partner_production')
    op.drop_index(op.f('ix_partners_primary_rep_id'), table_name='partners')
    op.drop_table('partners')
    op.drop_index('uq_users_email_live', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_table('carriers')
    # ### end Alembic commands ###
