"""audit events

Revision ID: 11ca8b77f2bc
Revises: 1c76491e10f2
Create Date: 2026-09-30 10:33:35.104342
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '11ca8b77f2bc'
down_revision: str | Sequence[str] | None = '1c76491e10f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('actor_kind', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('referral_id', sa.Uuid(), nullable=True),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("(actor_kind = 'user') = (actor_id IS NOT NULL)", name=op.f('ck_audit_events_user_actor_has_id')),
    sa.CheckConstraint("action IN ('insert', 'update', 'delete', 'restore')", name=op.f('ck_audit_events_action')),
    sa.CheckConstraint("actor_kind IN ('user', 'job', 'script', 'system')", name=op.f('ck_audit_events_actor_kind')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity', 'entity_id'], unique=False)
    op.create_index('ix_audit_events_partner', 'audit_events', ['partner_id', 'occurred_at'], unique=False, postgresql_where=sa.text('partner_id IS NOT NULL'))
    op.create_index('ix_audit_events_referral', 'audit_events', ['referral_id', 'occurred_at'], unique=False, postgresql_where=sa.text('referral_id IS NOT NULL'))
    # ### end Alembic commands ###

    # Append-only, enforced by the database itself (written by hand: autogenerate can't see triggers).
    # Rows can be added, never changed or removed. TRUNCATE is refused too, unless the transaction sets
    # canyon.allow_audit_reset = 'on', which only the seed script does (localhost or the demo only).
    # With real data in production, a separate database role without UPDATE/DELETE/TRUNCATE on this table
    # goes further still; see DECISIONS.md.
    op.execute("""
        CREATE FUNCTION audit_events_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'TRUNCATE' AND current_setting('canyon.allow_audit_reset', true) = 'on' THEN
                RETURN NULL;
            END IF;
            RAISE EXCEPTION 'audit_events is append-only: % refused', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER audit_events_no_change BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()
    """)
    op.execute("""
        CREATE TRIGGER audit_events_no_truncate BEFORE TRUNCATE ON audit_events
        FOR EACH STATEMENT EXECUTE FUNCTION audit_events_append_only()
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER audit_events_no_truncate ON audit_events")
    op.execute("DROP TRIGGER audit_events_no_change ON audit_events")
    op.execute("DROP FUNCTION audit_events_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_referral', table_name='audit_events', postgresql_where=sa.text('referral_id IS NOT NULL'))
    op.drop_index('ix_audit_events_partner', table_name='audit_events', postgresql_where=sa.text('partner_id IS NOT NULL'))
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
