"""activities

Revision ID: e84645b35b65
Revises: d6a20eecc99d
Create Date: 2026-09-29 15:51:36.897042
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e84645b35b65'
down_revision: str | Sequence[str] | None = 'd6a20eecc99d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('referral_id', sa.Uuid(), nullable=True),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('rep_id', sa.Uuid(), nullable=False),
    sa.Column('logged_by_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), server_default='', nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("method IN ('In person', 'Phone', 'Email')", name=op.f('ck_activities_method')),
    sa.CheckConstraint('char_length(notes) <= 2000', name=op.f('ck_activities_notes_length')),
    sa.CheckConstraint('num_nonnulls(referral_id, partner_id) = 1', name=op.f('ck_activities_one_parent')),
    sa.ForeignKeyConstraint(['logged_by_id'], ['users.id'], name=op.f('fk_activities_logged_by_id_users')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_activities_partner_id_partners')),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_activities_referral_id_referrals')),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], name=op.f('fk_activities_rep_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_partner_id'), 'activities', ['partner_id'], unique=False)
    op.create_index(op.f('ix_activities_referral_id'), 'activities', ['referral_id'], unique=False)
    op.create_index(op.f('ix_activities_rep_id'), 'activities', ['rep_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_rep_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_referral_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_partner_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
