"""goals

Revision ID: 46caf66e04e6
Revises: 3c6a534c6ce9
Create Date: 2026-09-29 21:23:01.006183
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '46caf66e04e6'
down_revision: str | Sequence[str] | None = '3c6a534c6ce9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_goals',
    sa.Column('singleton', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('close_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('close_rate IS NULL OR close_rate BETWEEN 0 AND 1', name=op.f('ck_company_goals_close_rate')),
    sa.CheckConstraint('singleton', name=op.f('ck_company_goals_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_goals'))
    )
    op.create_index('uq_company_goals_singleton_live', 'company_goals', ['singleton'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('rep_goals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('clients', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sales', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('clients >= 0', name=op.f('ck_rep_goals_clients')),
    sa.CheckConstraint('sales >= 0', name=op.f('ck_rep_goals_sales')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rep_goals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rep_goals'))
    )
    op.create_index('uq_rep_goals_user_id_live', 'rep_goals', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_rep_goals_user_id_live', table_name='rep_goals', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('rep_goals')
    op.drop_index('uq_company_goals_singleton_live', table_name='company_goals', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('company_goals')
    # ### end Alembic commands ###
