"""notifications

Revision ID: 1c76491e10f2
Revises: 46caf66e04e6
Create Date: 2026-09-30 09:47:55.519542
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1c76491e10f2'
down_revision: str | Sequence[str] | None = '46caf66e04e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('referral_id', sa.Uuid(), nullable=True),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(kind = 'stale_referral') = (referral_id IS NOT NULL)", name=op.f('ck_notifications_referral_for_stale')),
    sa.CheckConstraint("kind IN ('stale_referral', 'weekly_digest')", name=op.f('ck_notifications_kind')),
    sa.CheckConstraint('char_length(dedupe_key) BETWEEN 1 AND 200', name=op.f('ck_notifications_dedupe_key_length')),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_notifications_referral_id_referrals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('uq_notifications_user_id_dedupe_key_live', 'notifications', ['user_id', 'dedupe_key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notifications_user_id_dedupe_key_live', table_name='notifications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('notifications')
    # ### end Alembic commands ###
