"""sign in

Revision ID: 611fb7899f27
Revises: 11ca8b77f2bc
Create Date: 2026-09-30 10:51:12.929407
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '611fb7899f27'
down_revision: str | Sequence[str] | None = '11ca8b77f2bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('email_key', sa.String(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_at', 'login_attempts', ['attempted_at'], unique=False)
    op.create_index('ix_login_attempts_key_at', 'login_attempts', ['email_key', 'attempted_at'], unique=False)
    op.create_table('account_links',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("purpose IN ('setup', 'reset')", name=op.f('ck_account_links_purpose')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_account_links_created_by_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_links_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_links'))
    )
    op.create_index('ix_account_links_user_id', 'account_links', ['user_id'], unique=False)
    op.create_index('uq_account_links_token_hash_live', 'account_links', ['token_hash'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index('uq_sessions_token_hash_live', 'sessions', ['token_hash'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'password_hash')
    op.drop_index('uq_sessions_token_hash_live', table_name='sessions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('uq_account_links_token_hash_live', table_name='account_links', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_account_links_user_id', table_name='account_links')
    op.drop_table('account_links')
    op.drop_index('ix_login_attempts_key_at', table_name='login_attempts')
    op.drop_index('ix_login_attempts_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
